# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  name "engram"
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/Gentleman-Programming/engram"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  on_macos do
    on_intel do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
      sha256 "fee8536d7ea4b3bc4dd489e8bfe8ad75bdd4b663357036aabeaec846d7b3fe07"
    end
    on_arm do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
      sha256 "a963d83f813a25c62ec802c8f87becb0909820c7bc72155a6c797e3ff84acac3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
      sha256 "eebbac8e7ff63ed3f6563d48f091f35340883c9a82aa3d86fb5b135fd0631e51"
    end
    on_arm do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
      sha256 "0e45a1743ea87296f84f32626b91161467c5c0003bf862c432de3bf34495222f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
