# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  name "engram"
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/Gentleman-Programming/engram"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  on_macos do
    on_intel do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
      sha256 "cad6f90fde6b5069329c557358a6f87ec3a2739b4261fa3b172b3c88617a11ea"
    end
    on_arm do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
      sha256 "34dde5c8483d1c05787e530db03998c307c2a2c946cbaec062154d911f07f70e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
      sha256 "20a83a0be3f36555ff040fe3807f560344c230eebf6da1c008eb002e9d41fa3a"
    end
    on_arm do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
      sha256 "43a4e9b20362519bac743c51244f35cf38284a3ae2edce5239053defdc770c22"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
