# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  name "engram"
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/Gentleman-Programming/engram"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  on_macos do
    on_intel do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
      sha256 "92c7b4c023a178a61f0bd07c1b7c5b0f2bc8ddf497a1ac5245fea2d0fca7c7a7"
    end
    on_arm do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
      sha256 "d2eb6b27e042cffb38d3f0773c49b8de6939d227e522eeaa3416fc60e715d373"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
      sha256 "7f35c8ea70d0edb2a4c8d13ade5d819495cb7412d09445f6fb4de69a27784a9e"
    end
    on_arm do
      url "https://github.com/Gentleman-Programming/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
      sha256 "2c4f2c70d8292bc20d3873702a4ee062ddd5cde3ae049554ad909b4508a52b7d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
