# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/Gentleman-Programming/engram"
  version "1.10.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.10.5/engram_1.10.5_darwin_amd64.tar.gz"
      sha256 "c3b0d4523485839c4bf7f6dc01f932e7733773fb178f83957ff867edc6032a8d"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.10.5/engram_1.10.5_darwin_arm64.tar.gz"
      sha256 "896c67a35e78d48b1380647917b33b4cf446ad687181f369f09bb1fe772d84c7"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.10.5/engram_1.10.5_linux_amd64.tar.gz"
      sha256 "10c23ace8384cf44cf42bff80f8c56fd441ae497a50706488b4ef718054e8678"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.10.5/engram_1.10.5_linux_arm64.tar.gz"
      sha256 "eec3dc09e6667b3454b10b42e4b637f49c91350c07723376112e1ea0975a2aaa"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end
end
