# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/Gentleman-Programming/engram"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.14.0/engram_1.14.0_darwin_amd64.tar.gz"
      sha256 "72ca611dc594ffd7e511fa89b828298f8d5567bc0f99bd66fe091e1fd4d3b82a"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.14.0/engram_1.14.0_darwin_arm64.tar.gz"
      sha256 "5602e178172aa81a57c7ba69386d38f18c75797fadb944d3acc11219d5c133e6"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.14.0/engram_1.14.0_linux_amd64.tar.gz"
      sha256 "836604301783b18c0f489c63b12202bd097567547ff4151d86a4120b8f28aa4c"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.14.0/engram_1.14.0_linux_arm64.tar.gz"
      sha256 "fb37afd038fb838511194694157825adad4d1182859cb46d765c082ebf99b275"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end
end
