# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/Gentleman-Programming/engram"
  version "1.15.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.15.11/engram_1.15.11_darwin_amd64.tar.gz"
      sha256 "546c8586312a7561ed318b57114acae4ee574f8bc3195d791c72902dcdbc7e5b"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.15.11/engram_1.15.11_darwin_arm64.tar.gz"
      sha256 "771e73660d6d730333fe7d77e1d8c4b2c5eeda176cf384498a1689774ecbb8e0"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.15.11/engram_1.15.11_linux_amd64.tar.gz"
      sha256 "e1d7c12f4b7a50b02b858d6ac47aa4093eb087a51a33ef4805c6dac08ffd664d"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/engram/releases/download/v1.15.11/engram_1.15.11_linux_arm64.tar.gz"
      sha256 "973cc7becc45714dded7891b930fb053d5600e41efd2b68b7f2d0518bf50ca6e"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end
end
