# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentlemanAi < Formula
  desc "AI Gentle Stack — One command to configure any AI coding agent on any OS."
  homepage "https://github.com/Gentleman-Programming/gentleman-ai-installer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/gentleman-ai-installer/releases/download/v0.1.0/gentleman-ai_0.1.0_darwin_amd64.tar.gz"
      sha256 "a08f0191f115a5bc3a7716a3cd7605af25462bd634996acdaaa4f2b5a9e8bb9b"

      define_method(:install) do
        bin.install "gentleman-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/gentleman-ai-installer/releases/download/v0.1.0/gentleman-ai_0.1.0_darwin_arm64.tar.gz"
      sha256 "72ffdfa8f6145ac7dad14bbb5567f54275efa2aa4bf5b0ec3ab3c1ce30e9ebf5"

      define_method(:install) do
        bin.install "gentleman-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentleman-ai-installer/releases/download/v0.1.0/gentleman-ai_0.1.0_linux_amd64.tar.gz"
      sha256 "e72b1da8006c07ffdd5a053f51f21a22998857fe7fa896b09803473e1ee9392f"
      define_method(:install) do
        bin.install "gentleman-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentleman-ai-installer/releases/download/v0.1.0/gentleman-ai_0.1.0_linux_arm64.tar.gz"
      sha256 "f2ee85357099f38fcc668f9f56577ab25a9a2eee44e8220e2300bc73c482a8d2"
      define_method(:install) do
        bin.install "gentleman-ai"
      end
    end
  end
end
