# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleAi < Formula
  desc "Gentle-AI — Ecosystem, Frameworks, Workflows for AI coding agents."
  homepage "https://github.com/Gentleman-Programming/gentle-ai"
  version "3.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v3.0.0/gentle-ai_3.0.0_darwin_amd64.tar.gz"
      sha256 "60f9a63d72d94a723817767a7c6932625868945349a6d39cdafdfd13ad9d53d1"

      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v3.0.0/gentle-ai_3.0.0_darwin_arm64.tar.gz"
      sha256 "4c6162fe35258f1168f4d2082f7ce92ad8d08f1b2653417b896ead5b9bad4bae"

      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v3.0.0/gentle-ai_3.0.0_linux_amd64.tar.gz"
      sha256 "3390c2fffdf255a744c6f39a10b01eba5441d77972e6d384602c6b6e125b616a"
      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v3.0.0/gentle-ai_3.0.0_linux_arm64.tar.gz"
      sha256 "3511ebb9ce2775850ecfb1326d7772b10d5c477de20e578baa936fda60eeca55"
      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
  end
end
