# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleAiAT1460 < Formula
  desc "Gentle-AI — Ecosystem, Frameworks, Workflows for AI coding agents."
  homepage "https://github.com/Gentleman-Programming/gentle-ai"
  version "1.46.0"
  license "MIT"

  conflicts_with "gentle-ai", because: "both install a 'gentle-ai' binary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.46.0/gentle-ai_1.46.0_darwin_amd64.tar.gz"
      sha256 "7f5030f9e117f5408cbae92df96da7a408b9b136e93823173f4f271bf9ea23bd"

      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.46.0/gentle-ai_1.46.0_darwin_arm64.tar.gz"
      sha256 "f239f1887f013b440a15e31cf1508ab0374a45c24a3b3653a0081789c345c322"

      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.46.0/gentle-ai_1.46.0_linux_amd64.tar.gz"
      sha256 "4928786f12b48d6a485076c42547f968b2d7b010b8f36a68e7e2073ba9f0a2da"
      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.46.0/gentle-ai_1.46.0_linux_arm64.tar.gz"
      sha256 "b9f248d83361671b8a912b821eaf8722175cce586dc2b2bea4c756766d17d218"
      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
  end
end
