# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GentleAi < Formula
  desc "AI Gentle Stack — One command to configure any AI coding agent on any OS."
  homepage "https://github.com/Gentleman-Programming/gentle-ai"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.6.0/gentle-ai_1.6.0_darwin_amd64.tar.gz"
      sha256 "a44eabb7bead9f36f680e85041103210fad6eef5132d03f8096b2657131be6cb"

      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.6.0/gentle-ai_1.6.0_darwin_arm64.tar.gz"
      sha256 "1a54ccbb9e1b2e30e2e7432140fdab22e1b3cb115f2e382a3a4409c1aece72ee"

      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.6.0/gentle-ai_1.6.0_linux_amd64.tar.gz"
      sha256 "e87a2aa45f395ea415afe88171329f381bbb34783c66d27d1e55d4e7e817b100"
      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gentleman-Programming/gentle-ai/releases/download/v1.6.0/gentle-ai_1.6.0_linux_arm64.tar.gz"
      sha256 "d4651101b8920876d15e568a5d441ee7c81b636835345a0e7bb19ebba7d334b6"
      define_method(:install) do
        bin.install "gentle-ai"
      end
    end
  end
end
